services:

  postgres:
    image: postgres:16
    container_name: eventhub-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: eventhub_auth
      POSTGRES_USER: eventhub
      POSTGRES_PASSWORD: eventhub123

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U eventhub -d eventhub_auth"]
      interval: 5s
      timeout: 5s
      retries: 10


  authservice:
    build:
      context: .
      dockerfile: src/EventHub.AuthService/Dockerfile

    container_name: eventhub-authservice
    restart: unless-stopped

    depends_on:
      postgres:
        condition: service_healthy

    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080

      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=eventhub_auth;Username=eventhub;Password=eventhub123"

    ports:
      - "5001:8080"


volumes:
  postgres_data: